import SwiftUI

struct OnboardingView: View {
    @AppStorage("didCompleteOnboarding") private var didCompleteOnboarding = false
    @AppStorage("appLanguage") private var appLanguage = AppLanguage.english.rawValue
    @AppStorage("trade") private var savedTrade = Trade.nail.rawValue
    @AppStorage("payModel") private var savedPayModel = PayModel.booth.rawValue
    @AppStorage("rentCents") private var savedRentCents = 25000
    @AppStorage("rentPeriod") private var savedRentPeriod = RentPeriod.week.rawValue
    @AppStorage("commissionCutBasisPoints") private var commissionCutBasisPoints = 5500
    @State private var step = 0; @State private var trade: Trade = .nail; @State private var payModel: PayModel = .booth; @State private var rent = "250"; @State private var rentPeriod: RentPeriod = .week; @State private var commission = "55"

    var body: some View { ZStack { Brand.page.ignoresSafeArea(); VStack(spacing: 0) { HStack { if step > 0 { Button(AppLanguage.current(appLanguage).backTitle) { withAnimation { step -= 1 } }.font(Brand.font(16)).foregroundStyle(Brand.hotPink) }; Spacer(); LanguagePicker(selection: $appLanguage) }.padding(.horizontal, Brand.screenPadding).padding(.top, 12); progress.padding(.horizontal, Brand.screenPadding).padding(.top, 14); Group { switch step { case 0: tradeStep; case 1: payStep; case 2: moneyStep; default: doneStep } }.frame(maxWidth: .infinity, maxHeight: .infinity) } }.foregroundStyle(Brand.ink) }
    private var progress: some View { HStack(spacing: 8) { ForEach(0..<4, id: \.self) { index in Capsule().fill(index <= step ? Brand.hotPink : Brand.line).frame(height: 6) } }.accessibilityHidden(true) }
    private var tradeStep: some View { ChoiceStep(title: L("onboarding.trade.title", language: appLanguage)) { ForEach(Trade.allCases) { item in ChoiceButton(title: L(String.LocalizationValue(item.titleKey), language: appLanguage), symbol: symbol(for: item), selected: trade == item) { trade = item; withAnimation(.snappy(duration: 0.2)) { step = 1 } } } } }
    private var payStep: some View { ChoiceStep(title: L("onboarding.pay.title", language: appLanguage)) { ChoiceButton(title: L("pay.booth", language: appLanguage), symbol: "chair.lounge.fill", selected: payModel == .booth) { payModel = .booth; step = 2 }; ChoiceButton(title: L("pay.commission", language: appLanguage), symbol: "percent", selected: payModel == .commission) { payModel = .commission; step = 2 }; ChoiceButton(title: L("pay.hybrid", table: "Hybrid", language: appLanguage), symbol: "plusminus", selected: payModel == .hybrid) { payModel = .hybrid; step = 2 } } }
    private var moneyStep: some View { VStack(alignment: .leading, spacing: 22) { Spacer(); if payModel != .commission { Text(L("rent.weekly", language: appLanguage)).font(Brand.font(24, weight: .heavy)); MoneyEntryField(text: $rent, prefix: "$", suffix: nil); Text(L("settings.rentPeriod", language: appLanguage)).font(Brand.font(18)); Picker(L("settings.rentPeriod", language: appLanguage), selection: $rentPeriod) { Text(L("rent.week", language: appLanguage)).tag(RentPeriod.week); Text(L("rent.month", language: appLanguage)).tag(RentPeriod.month) }.pickerStyle(.segmented).frame(height: 56) }; if payModel != .booth { Text(L("settings.serviceSplit", table: "Hybrid", language: appLanguage)).font(Brand.font(24, weight: .heavy)); MoneyEntryField(text: $commission, prefix: nil, suffix: "%") }; Spacer(); PrimaryButton(title: L("onboarding.cta", language: appLanguage)) { saveDefaults(); step = 3 } }.padding(Brand.screenPadding) }
    private var doneStep: some View { VStack(spacing: 30) { Spacer(); Text(L("onboarding.done", language: appLanguage)).font(Brand.font(36, weight: .heavy)).foregroundStyle(.white).multilineTextAlignment(.center); Spacer(); PrimaryButton(title: L("onboarding.cta", language: appLanguage)) { didCompleteOnboarding = true } }.padding(Brand.screenPadding).background(Brand.page) }
    private func saveDefaults() { savedTrade = trade.rawValue; savedPayModel = payModel.rawValue; if payModel != .commission { savedRentCents = MoneyMath.cents(from: rent); savedRentPeriod = rentPeriod.rawValue }; if payModel != .booth { commissionCutBasisPoints = MoneyMath.basisPoints(fromPercentText: commission, fallback: 5500) } }
    private func symbol(for trade: Trade) -> String { switch trade { case .nail: "hand.raised.fill"; case .hair: "scissors"; case .barber: "scissors"; case .esthetician: "sparkles" } }
}
private struct ChoiceStep<Content: View>: View { let title: String; @ViewBuilder let content: Content; var body: some View { VStack(alignment: .leading, spacing: 28) { Spacer(); Text(title).font(Brand.font(32, weight: .heavy)); VStack(spacing: 16) { content }; Spacer() }.padding(Brand.screenPadding) } }
struct ChoiceButton: View { let title: String; let symbol: String; let selected: Bool; let action: () -> Void; var body: some View { Button(action: action) { HStack(spacing: 18) { Image(systemName: symbol).font(.system(size: 25, weight: .bold)).frame(width: 34); Text(title).font(Brand.font(20)); Spacer(); Image(systemName: "chevron.right").font(.system(size: 18, weight: .bold)) }.foregroundStyle(Brand.ink).padding(.horizontal, 20).frame(minHeight: 68).background(selected ? Brand.berry : Brand.surface).clipShape(RoundedRectangle(cornerRadius: Brand.controlRadius)).overlay { RoundedRectangle(cornerRadius: Brand.controlRadius).stroke(selected ? Brand.hotPink : Brand.line, lineWidth: selected ? 3 : 2) } }.buttonStyle(.plain) } }
struct PrimaryButton: View { let title: String; let action: () -> Void; var body: some View { Button(action: action) { Text(title).font(Brand.font(20, weight: .heavy)).foregroundStyle(.white).frame(maxWidth: .infinity, minHeight: Brand.controlHeight).background(Brand.hotPink).clipShape(RoundedRectangle(cornerRadius: Brand.controlRadius)) }.buttonStyle(.plain) } }
struct MoneyEntryField: View { @Binding var text: String; let prefix: String?; let suffix: String?; @FocusState private var focused: Bool; var body: some View { HStack(spacing: 8) { if let prefix { Text(prefix) }; TextField("0", text: $text).keyboardType(.decimalPad).focused($focused); if let suffix { Text(suffix) } }.font(Brand.font(32, weight: .heavy)).padding(.horizontal, 20).frame(minHeight: 64).background(Brand.surface).clipShape(RoundedRectangle(cornerRadius: Brand.controlRadius)).overlay(RoundedRectangle(cornerRadius: Brand.controlRadius).stroke(focused ? Brand.hotPink : Brand.line, lineWidth: focused ? 3 : 2)) } }
